# -*- coding: utf-8 -*-
# vim: ft=yaml
---
minimum_pre_commit_version: 2.7.1
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-vcs-permalinks
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        additional_dependencies:
          - "salt==3001.3"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        additional_dependencies:
          - "tokenize-rt==3.2.0"
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.3
    hooks:
      - id: bandit
        args:
          - "-iii"
          - "-ll"
