# -*- coding: utf-8 -*-
# vim: ft=yaml
---
dist: xenial
services:
  - docker
language: python

install:
  - pip install tox

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - SALT=v3001.3 BACKEND=cherrypy
  - SALT=v3001.3 BACKEND=tornado
  - SALT=v3002.2 BACKEND=cherrypy
  - SALT=v3002.2 BACKEND=tornado
  - SALT=develop BACKEND=cherrypy
  - SALT=develop BACKEND=tornado

matrix:
  allow_failures:
    - python: "3.8"
    - env: SALT=develop BACKEND=tornado
    - env: SALT=develop BACKEND=cherrypy

script:
  - PYTHON="${TRAVIS_PYTHON_VERSION/-dev/-rc}"
  - TOX_VERSION="py${PYTHON//./}"
  - docker run -v $PWD:/pepper -ti --rm "python:$PYTHON" make -C /pepper test PYVERSION="${TOX_VERSION%-rc}" SALT="${SALT}" BACKEND="${BACKEND}"

after_success:
  - sudo chown $USER .tox/
  - tox -e codecov
