#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CLI entry point for pepper."""

# Import Python Libraries
import logging
from logging import NullHandler
from typing import Any, Literal, Union

# Import Pepper Libraries
import pepper.script

logging.basicConfig(format="%(levelname)s %(asctime)s %(module)s: %(message)s")
logger: logging.Logger = logging.getLogger("pepper")
logger.addHandler(NullHandler())


if __name__ == "__main__":
    exit_code: Union[Any, Literal[0, -1, 1], None] = pepper.script.Pepper()()
    raise SystemExit(exit_code if exit_code is not None else 0)
